### ISSUE TITLE
Real buttons on the front work, but the buttons provided by the integration do not (RX-V475 model)

### ISSUE THREAD

**Issue by solnitza** [mvdwetering/yamaha_ynca#19]
I have a Yamaha RX-V475 receiver. In the HA dashboard I have four buttons that do not work:
Yamaha RX-V475 Main: BD/DVD
Yamaha RX-V475 Main: TV
Yamaha RX-V475 Main: NET
Yamaha RX-V475 Main: RADIO

Although, by selecting the source in the Main controls I can activate each of those sources.

**Diagnostics**
[config_entry-yamaha_ynca-18b044fe695d0f0f1541cc289f90b780.json.txt](https://github.com/mvdwetering/yamaha_ynca/files/9489478/config_entry-yamaha_ynca-18b044fe695d0f0f1541cc289f90b780.json.txt)

**Logging**
There are no errors. Logs are like this:

September 5, 2022
Yamaha RX-V475 Main: TV changed to September 5, 2022 at 2:42 PM triggered by service button.press
2:42:16 PM - 6 minutes ago - Valentin
Yamaha RX-V475 Main changed to Idle triggered by service media_player.select_source
1:10:24 PM - 2 hours ago - Valentin
Yamaha RX-V475 Main turned on triggered by service media_player.select_source
1:10:19 PM - 2 hours ago - Valentin
Yamaha RX-V475 Main: RADIO changed to September 5, 2022 at 1:08 PM triggered by service button.press
1:08:29 PM - 2 hours ago - Valentin
Yamaha RX-V475 Main: NET changed to September 5, 2022 at 1:08 PM triggered by service button.press
1:08:28 PM - 2 hours ago - Valentin
Yamaha RX-V475 Main: TV changed to September 5, 2022 at 1:08 PM triggered by service button.press
1:08:27 PM - 2 hours ago - Valentin
Yamaha RX-V475 Main: BD/DVD changed to September 5, 2022 at 1:08 PM triggered by service button.press
1:08:26 PM - 2 hours ago - Valentin
Yamaha RX-V475 Main: TV changed to September 5, 2022 at 1:06 PM triggered by service button.press
1:06:18 PM - 2 hours ago - Valentin
Yamaha RX-V475 Main: RADIO changed to September 5, 2022 at 1:06 PM triggered by service button.press
1:06:17 PM - 2 hours ago - Valentin
Yamaha RX-V475 Main: NET changed to September 5, 2022 at 1:06 PM triggered by service button.press
1:06:16 PM - 2 hours ago - Valentin
Yamaha RX-V475 Main: BD/DVD changed to September 5, 2022 at 1:06 PM triggered by service button.press
1:06:14 PM - 2 hours ago - Valentin

**Home Assistant version information:**
 - Version [e.g. 2022.8.6]

**Comment by mvdwetering** [comment]
It turns out that errors returned by the receiver were not logged in the diagnostics data. I fixed that in the new 4.5.0 release.

Could you update to the 4.5.0 release or newer and press the buttons again in Home Assistant and then download the diagnostics and attach it here in a comment?

**Comment by solnitza** [comment]
Hello.
I have the 4.5.0 release, and these are the diagnostics after pressing each of those buttons.

[config_entry-yamaha_ynca-18b044fe695d0f0f1541cc289f90b780.json.txt](https://github.com/mvdwetering/yamaha_ynca/files/9500014/config_entry-yamaha_ynca-18b044fe695d0f0f1541cc289f90b780.json.txt)

**Comment by mvdwetering** [comment]
Thanks for the diagnostics, it really helps to see the actual data from the real device.

I see that when sending the command to activate a scene the receiver responds with "RESTRICTED" which usually means that the command-is-known-but-it-can-not-be-applied-right-now, like for example trying to change the input when the receiver is Off. When sending an invalid scene name to my own receiver it responds with "UNDEFINED" so it behaves differently, not entirely sure what to think of it. I guess that in this case "RESTRICTED" also means it just does not work for some reason.

Unfortunately it seems that the command is just not supported by your receiver. Which is kind of weird since I can get the names of the scenes, so why can't I activate them...
Anyway, unless we find some documentation on if/how this would work for your receiver model I guess we are stuck :( 

Because I don't see a way to detect if scene activation is supported I suggest you disable the button entities in Home Assistant.

**Comment by solnitza** [comment]
Thank you for trying. I don't mind if those buttons don't work. I can always set up an automation to turn on the receiver and then select the desired source. 
Regarding the RESTRICTED response when "trying to change the input when the receiver is Off", I think it should work even when it is off, as the 4 physical buttons are also turning on the receiver when pressed, beside selecting the source.
I will try to find some more documentation or see if there are more setup options of the receiver that I missed.

Apart from this issue, can I ask if a Sound mode can be added (5ch Stereo)? My receiver has 2ch and 5ch options, and the current list in the integration includes 2ch, 7ch, and 9ch.

Thanks.

**Comment by mvdwetering** [comment]
I tried contacting Yamaha about the protocol specs a while back, but apparently these specs are only handed out to licenced installers. If you manage to find some documentation, please let me know as I am very interested. 

I will add the 5ch stereo to the list.

**Comment by mvdwetering** [comment]
5ch Stereo is added in the 4.7.0 release along with a method to hide soundmodes that do not apply to a receiver.

On that note, if you can send me a list of all supported soundmodes by your model I can add it to the modelinfo so it will match the receiver automatically.

I suspect the list will be the same as the "basic" list, with 5ch Stereo instead of 7ch Stereo
https://github.com/mvdwetering/ynca/blob/master/ynca/modelinfo.py#L14 (line 14-34)

**Comment by solnitza** [comment]
Thanks for adding the 5ch option.

Regarding the supported sound modes, they are selectable with different buttons on the remote.

For the Music button:

HALL_IN_MUNICH,
HALL_IN_VIENNA,
CHAMBER,
CELLAR_CLUB,
THE_ROXY_THEATRE,
THE_BOTTOM_LINE,
MUSIC_VIDEO,
TWO_CH_STEREO,
FIVE_CH_STEREO

For the Movie Button:
 
SPORTS,
ACTION_GAME,
ROLEPLAYING_GAME,
STANDARD,
SPECTACLE,
SCI_FI,
ADVENTURE,
DRAMA,
MONO_MOVIE

I don't have a SURROUND_DECODER option. There is a button on the remote named that way, and it has these options: 

Dolby Pro Logic,
Dolby PLII Movie,
Dolby PLII Music, 
Dolby PLII Game, 
Neo:6 Cinema, 
Neo:6 Music

**Comment by mvdwetering** [comment]
I added the RX-V475 modelinfo in relesase v4.8.0 so now the list of soundmodes should match the ones on the devices.

It turns out the SurroundDecoder mode is a bit special.
When selecting something like "Neo:6 Cinema" the receiver under the hood sets the SoundPrg (as it is called in the YNCA protocol) to SurroundDecoder and another setting called "2CHDECODER" to "Neo:6 Cinema".

Adding those Surround soundmodes is a bit tricky as under the hood multiple settings are interacting and I am not entirely sure how it works. So I will create a reminder issue to look at that at some point.

**Comment by mvdwetering** [comment]
I think we are done on this topic, so closing the issue.
