### ISSUE TITLE
It is not possible to increase through INITIAL VOLUME

### ISSUE THREAD

**Issue by gilad3121** [mvdwetering/yamaha_ynca#229]
have a Yamaha receiver RX-A1040 and I want to increase the volume more than the home assistant gives between 0-1, I found in HACS that there is an integration called YNCA and it gave me the option to see the initial volume and that it will control the receiver for me through the home assistant, but when I increase through it, it does not affect the volume

I installed through the HACS, then in INTEGRATION you restarted the home assistant and the receiver turned up for me through the integration

I expected that when I increase there it will really increase and for some reason it has no effect
Attach a picture
![418182949_10219332084692819_6582469572535552884_n](https://github.com/mvdwetering/yamaha_ynca/assets/91723759/faca56dc-ca6b-4fd9-9294-54adccc03f81)

Core
2024.1.2
Supervisor
2023.12.0
Operating System
11.4
Frontend
20240104.0

**Comment by gilad3121** [comment]
Initial volume is the volume that is automatically set when turning the device on

**Comment by mvdwetering** [comment]
Note that this integration already  maps the whole volume range supported by the receiver to the 0-1 range required by Home Assistant so there is not need to use other volume controls to get the whole volume range of the receiver. 
The max of the whole volume range is still limited to the maxvolume option you configured on the receiver.

In case you want to have a easier/clearer mapping of normal volume values in dB to the 0-1 range in Home Assistant you could enable the "Volume (dB)" entity (it is default disabled because it is not the standard way to do voume in HA). It is basically the same as the volume in the mediaplayer, but it uses the dB unit so you can use the same values on the receiver without trying to guess the HA number..
